python main_cnn.py --data_path data/BPI_Challenge_2012C.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPI_Challenge_2012C.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPI_Challenge_2012C.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPI_Challenge_2012C.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPI_Challenge_2012C.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPI_Challenge_2012C.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPI_Challenge_2012C.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPI_Challenge_2012C.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPI_Challenge_2012C.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPIC15_1.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPIC15_1.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPIC15_1.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPIC15_1.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPIC15_1.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPIC15_1.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPIC15_1.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPIC15_1.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPIC15_1.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPIC20_DomesticDeclarations.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPIC20_DomesticDeclarations.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPIC20_DomesticDeclarations.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPIC20_DomesticDeclarations.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPIC20_DomesticDeclarations.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPIC20_DomesticDeclarations.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPIC20_DomesticDeclarations.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPIC20_DomesticDeclarations.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPIC20_DomesticDeclarations.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPIC20_InternationalDeclarations.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPIC20_InternationalDeclarations.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPIC20_InternationalDeclarations.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPIC20_InternationalDeclarations.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPIC20_InternationalDeclarations.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPIC20_InternationalDeclarations.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPIC20_InternationalDeclarations.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPIC20_InternationalDeclarations.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPIC20_InternationalDeclarations.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPI_Challenge_2013_incidents.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPI_Challenge_2013_incidents.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPI_Challenge_2013_incidents.csv --tasks next_activity --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPI_Challenge_2013_incidents.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPI_Challenge_2013_incidents.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPI_Challenge_2013_incidents.csv --tasks next_time --model CNN --epochs 200 --learning_rate 0.001 --seed 2025
python main_cnn.py --data_path data/BPI_Challenge_2013_incidents.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 42
python main_cnn.py --data_path data/BPI_Challenge_2013_incidents.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 123
python main_cnn.py --data_path data/BPI_Challenge_2013_incidents.csv --tasks remaining_time --model CNN --epochs 200 --learning_rate 0.001 --seed 2025

